import {
  useEffect,
  useRef,
  useState,
} from "react";

import {
  useNavigate,
  useParams,
} from "react-router-dom";

import {
  MoreVertical,
  Upload,
  Download,
} from "lucide-react";

import api from "../services/api";
import { useAuth } from "../context/AuthContext";

import Timeline from "../components/editor/Timeline";
import EditorControls from "../components/editor/EditorControls";
import EditingRibbon from "../components/editor/EditingRibbon";
import PreviewWaveform from "../components/editor/PreviewWaveform";
import Loader from "../components/Loader";


const ProjectEditor = () => {
  const { projectId } = useParams();

  const navigate = useNavigate();
  const { user } = useAuth();

  const fileInputRef = useRef(null);
  const audioRef = useRef(null);
  const animationRef = useRef(null);
  const menuRef = useRef(null);


  // ==========================================
  // PROJECT
  // ==========================================

  const [project, setProject] =
    useState(null);

  const [loading, setLoading] =
    useState(true);

  const [uploading, setUploading] =
    useState(false);

  const [
    showProjectMenu,
    setShowProjectMenu,
  ] = useState(false);


  // ==========================================
  // COMPILED PREVIEW
  // ==========================================

  /*
    This is the ONE compiled audio file
    generated by Python.

    Even if the project has 10 clips,
    there is only one preview waveform.
  */

  const [
    previewUrl,
    setPreviewUrl,
  ] = useState(null);


  // ==========================================
  // SELECTED CLIP
  // ==========================================

  const [
    selectedClip,
    setSelectedClip,
  ] = useState(null);


  // ==========================================
  // PLAYBACK
  // ==========================================

  const [
    isPlaying,
    setIsPlaying,
  ] = useState(false);

  const [
    duration,
    setDuration,
  ] = useState(0);

  const [
    markerTime,
    setMarkerTime,
  ] = useState(0);


  // ==========================================
  // UNDO / REDO
  // ==========================================

  const [
    undoStack,
    setUndoStack,
  ] = useState([]);

  const [
    redoStack,
    setRedoStack,
  ] = useState([]);


  // ==========================================
  // TRACK MARKERS
  // ==========================================

  const [
    trackMarkers,
    setTrackMarkers,
  ] = useState({});


  // ==========================================
  // PROJECT DURATION FROM METADATA
  // ==========================================

  const calculateProjectDuration = (
    projectData
  ) => {
    const tracks =
      projectData?.state?.tracks || [];

    let maxEnd = 0;

    tracks.forEach((track) => {
      track.clips?.forEach((clip) => {
        const clipDuration =
          clip.sourceEnd -
          clip.sourceStart;

        const clipEnd =
          clip.timelineStart +
          clipDuration;

        maxEnd = Math.max(
          maxEnd,
          clipEnd
        );
      });
    });

    return maxEnd;
  };


  // ==========================================
  // CANCEL PLAYBACK ANIMATION
  // ==========================================

  const cancelPlaybackAnimation =
    () => {

      if (
        animationRef.current
      ) {
        cancelAnimationFrame(
          animationRef.current
        );

        animationRef.current =
          null;
      }
    };


  // ==========================================
  // INVALIDATE CURRENT PREVIEW
  // ==========================================

  const invalidatePreview = () => {
    const audio =
      audioRef.current;

    if (audio) {
      audio.pause();

      audio.removeAttribute(
        "src"
      );

      audio.load();
    }

    cancelPlaybackAnimation();

    setIsPlaying(false);


    /*
      IMPORTANT:

      Once project metadata changes,
      the previously generated waveform
      is no longer the current project.

      Remove it until Run/Play generates
      a fresh compiled preview.
    */

    setPreviewUrl(null);
  };


  // ==========================================
  // UPDATE PROJECT STATE
  // ==========================================

  const updateProjectState = async (
    newState,
    {
      recordHistory = true,
    } = {}
  ) => {
    if (!project) {
      return;
    }


    const previousState =
      structuredClone(
        project.state
      );


    if (recordHistory) {
      setUndoStack(
        (previous) => [
          ...previous,
          previousState,
        ]
      );

      setRedoStack([]);
    }


    // ========================================
    // OPTIMISTIC UPDATE
    // ========================================

    setProject((previous) => {
      if (!previous) {
        return previous;
      }

      const updatedProject = {
        ...previous,
        state: newState,
      };

      setDuration(
        calculateProjectDuration(
          updatedProject
        )
      );

      return updatedProject;
    });


    invalidatePreview();


    // ========================================
    // SAVE BACKEND
    // ========================================

    try {
      const response =
        await api.patch(
          `/projects/${projectId}/state`,
          {
            state: newState,
          }
        );

      setProject((previous) => {
        if (!previous) {
          return previous;
        }

        return {
          ...previous,

          version:
            response.data.version,
        };
      });

    } catch (error) {
      console.error(
        "Failed to save project state:",
        error
      );

      alert(
        "Failed to save project changes."
      );
    }
  };


  // ==========================================
  // UNDO
  // ==========================================

  const handleUndo = async () => {
    if (
      !project ||
      undoStack.length === 0
    ) {
      return;
    }


    const previousState =
      undoStack[
        undoStack.length - 1
      ];


    const currentState =
      structuredClone(
        project.state
      );


    setUndoStack(
      (previous) =>
        previous.slice(
          0,
          -1
        )
    );


    setRedoStack(
      (previous) => [
        ...previous,
        currentState,
      ]
    );


    await updateProjectState(
      structuredClone(
        previousState
      ),
      {
        recordHistory: false,
      }
    );


    setSelectedClip(null);
  };


  // ==========================================
  // REDO
  // ==========================================

  const handleRedo = async () => {
    if (
      !project ||
      redoStack.length === 0
    ) {
      return;
    }


    const nextState =
      redoStack[
        redoStack.length - 1
      ];


    const currentState =
      structuredClone(
        project.state
      );


    setRedoStack(
      (previous) =>
        previous.slice(
          0,
          -1
        )
    );


    setUndoStack(
      (previous) => [
        ...previous,
        currentState,
      ]
    );


    await updateProjectState(
      structuredClone(
        nextState
      ),
      {
        recordHistory: false,
      }
    );


    setSelectedClip(null);
  };


  // ==========================================
  // APPLY EFFECT
  // ==========================================

  const handleApplyEffect = async (
    effect
  ) => {
    if (!project) {
      return;
    }

    if (!selectedClip) {
      alert(
        "Select a clip before applying an effect."
      );

      return;
    }


    const previousState =
      structuredClone(
        project.state
      );


    try {
      const response =
        await api.post(
          `/projects/${projectId}/tracks/${selectedClip.trackId}/clips/${selectedClip.clipId}/effects`,
          {
            type:
              effect.type,

            parameters:
              effect.parameters || {},
          }
        );


      // Save previous state for undo

      setUndoStack(
        (previous) => [
          ...previous,
          previousState,
        ]
      );

      setRedoStack([]);


      // Use backend's updated project

      setProject(
        (previous) => {
          if (!previous) {
            return previous;
          }

          const updatedProject = {
            ...previous,

            version:
              response.data.project
                .version,

            state:
              response.data.project
                .state,
          };


          setDuration(
            calculateProjectDuration(
              updatedProject
            )
          );


          return updatedProject;
        }
      );


      invalidatePreview();


    } catch (error) {
      console.error(
        "Failed to apply effect:",
        error
      );

      alert(
        "Could not apply effect."
      );
    }
  };


  // ==========================================
  // PLAYBACK MARKER ANIMATION
  // ==========================================

  const updateMarkerAnimation =
    () => {

      const audio =
        audioRef.current;

      if (!audio) {
        return;
      }


      /*
        This marker time also drives
        PreviewWaveform.

        Therefore:
        audio plays
            ↓
        markerTime changes
            ↓
        waveform teal portion grows
      */

      setMarkerTime(
        audio.currentTime
      );


      if (
        !audio.paused &&
        !audio.ended
      ) {
        animationRef.current =
          requestAnimationFrame(
            updateMarkerAnimation
          );
      }
    };


  // ==========================================
  // CLEANUP
  // ==========================================

  useEffect(() => {
  const stopAudio = () => {
    const audio =
      audioRef.current;

    if (audio) {
      audio.pause();

      audio.currentTime = 0;

      audio.removeAttribute(
        "src"
      );

      audio.load();
    }

    cancelPlaybackAnimation();

    setIsPlaying(false);
  };


  const handleBeforeUnload = () => {
    stopAudio();
  };


  window.addEventListener(
    "beforeunload",
    handleBeforeUnload
  );


  return () => {
    window.removeEventListener(
      "beforeunload",
      handleBeforeUnload
    );

    stopAudio();
  };
}, []);


  // ==========================================
  // CLOSE THREE DOT MENU
  // ==========================================

  useEffect(() => {
    const handleOutsideClick = (
      event
    ) => {
      if (
        menuRef.current &&
        !menuRef.current.contains(
          event.target
        )
      ) {
        setShowProjectMenu(false);
      }
    };


    document.addEventListener(
      "mousedown",
      handleOutsideClick
    );


    return () => {
      document.removeEventListener(
        "mousedown",
        handleOutsideClick
      );
    };
  }, []);


  // ==========================================
  // LOAD PROJECT
  // ==========================================

  useEffect(() => {
    if (!user) {
      setLoading(false);
      return;
    }


    const loadProject =
      async () => {

        try {
          const response =
            await api.get(
              `/projects/${projectId}`
            );


          const loadedProject =
            response.data.project;


          setProject(
            loadedProject
          );


          setDuration(
            calculateProjectDuration(
              loadedProject
            )
          );


          setSelectedClip(null);

          setPreviewUrl(null);

          setUndoStack([]);

          setRedoStack([]);


        } catch (error) {
          console.error(
            "Failed to load project:",
            error
          );

        } finally {
          setLoading(false);
        }
      };


    loadProject();

  }, [
    projectId,
    user,
  ]);


  // ==========================================
  // OPEN FILE PICKER
  // ==========================================

  const handleUploadButton = () => {
    if (!user) {
      navigate("/login");
      return;
    }

    fileInputRef.current?.click();
  };


  // ==========================================
  // UPLOAD AUDIO
  // ==========================================

  const handleFileChange =
    async (event) => {

      const file =
        event.target.files?.[0];


      if (!file) {
        return;
      }


      const formData =
        new FormData();


      formData.append(
        "file",
        file
      );


      try {
        setUploading(true);


        const response =
          await api.post(
            `/projects/${projectId}/audio`,
            formData
          );


        const updatedProject = {
          ...project,

          version:
            response.data.project
              .version,

          state:
            response.data.project
              .state,
        };


        setProject(
          updatedProject
        );


        setDuration(
          calculateProjectDuration(
            updatedProject
          )
        );


        invalidatePreview();


      } catch (error) {
        console.error(
          "Audio upload failed:",
          error
        );

        alert(
          "Audio upload failed."
        );

      } finally {
        setUploading(false);

        event.target.value = "";
      }
    };


  // ==========================================
  // PLAY / PAUSE
  // ==========================================

  const handlePlayPause =
    async () => {

      const audio =
        audioRef.current;


      if (!audio) {
        return;
      }


      // ======================================
      // PAUSE CURRENT PREVIEW
      // ======================================

      if (isPlaying) {
        audio.pause();

        setMarkerTime(
          audio.currentTime
        );

        setIsPlaying(false);

        cancelPlaybackAnimation();

        return;
      }


      try {

        // ====================================
        // GENERATE COMPILED PREVIEW
        // ====================================

        const response =
          await api.post(
            `/projects/${projectId}/preview`
          );


        const generatedPreviewUrl =
          response.data.preview_url;


        const previewDuration =
          response.data.duration;


        /*
          Create one cache-busted URL and use
          exactly the same URL for:

          1. <audio>
          2. PreviewWaveform

          That guarantees the waveform being
          displayed represents the same compiled
          audio being played.
        */

        const playablePreviewUrl =
          `${generatedPreviewUrl}?v=${Date.now()}`;


        setPreviewUrl(
          playablePreviewUrl
        );


        setDuration(
          previewDuration
        );


        // ====================================
        // LOAD COMPILED AUDIO
        // ====================================

        audio.pause();

        cancelPlaybackAnimation();


        audio.src =
          playablePreviewUrl;


        audio.load();


        // ====================================
        // WAIT UNTIL AUDIO IS READY
        // ====================================

        await new Promise(
          (
            resolve,
            reject
          ) => {

            const handleReady = () => {
              cleanup();

              resolve();
            };


            const handleError = () => {
              cleanup();

              reject(
                new Error(
                  "Failed to load project preview."
                )
              );
            };


            const cleanup = () => {
              audio.removeEventListener(
                "loadedmetadata",
                handleReady
              );

              audio.removeEventListener(
                "error",
                handleError
              );
            };


            audio.addEventListener(
              "loadedmetadata",
              handleReady
            );


            audio.addEventListener(
              "error",
              handleError
            );
          }
        );


        // ====================================
        // START FROM GLOBAL MARKER
        // ====================================

        if (
          markerTime >=
          audio.duration
        ) {
          audio.currentTime = 0;

          setMarkerTime(0);

        } else {
          audio.currentTime =
            markerTime;
        }


        // ====================================
        // PLAY COMPILED AUDIO
        // ====================================

        await audio.play();


        setIsPlaying(true);


        animationRef.current =
          requestAnimationFrame(
            updateMarkerAnimation
          );


      } catch (error) {
        console.error(
          "Could not render/play project preview:",
          error
        );

        setIsPlaying(false);

        cancelPlaybackAnimation();
      }
    };


  // ==========================================
  // AUDIO ENDED
  // ==========================================

  const handleEnded = () => {
    const audio =
      audioRef.current;


    setIsPlaying(false);

    cancelPlaybackAnimation();


    if (audio) {
      setMarkerTime(
        audio.duration
      );
    }
  };


  // ==========================================
  // EXPORT
  // ==========================================

  const handleExport =
    async () => {

      setShowProjectMenu(false);


      try {
        const response =
          await api.post(
            `/projects/${projectId}/export`
          );


        const finalUrl =
          response.data.audio.url;


        const link =
          document.createElement(
            "a"
          );


        link.href =
          finalUrl;


        link.download =
          `${project.name}.wav`;


        document.body.appendChild(
          link
        );


        link.click();


        document.body.removeChild(
          link
        );


      } catch (error) {
        console.error(
          "Export failed:",
          error
        );

        alert(
          "Failed to export project."
        );
      }
    };


  // ==========================================
  // LOADING
  // ==========================================

  if (loading) {
    return (
      <div
        className="
          flex
          min-h-screen
          items-center
          justify-center
          bg-[var(--bg-main)]
        "
      >
        <Loader size={52} />
      </div>
    );
  }


  // ==========================================
  // NOT LOGGED IN
  // ==========================================

  if (!user) {
    return (
      <div
        className="
          flex
          min-h-screen
          flex-col
          items-center
          justify-center
          bg-[var(--bg-main)]
        "
      >
        <h2
          className="
            text-2xl
            font-bold
          "
        >
          Login required
        </h2>

        <button
          onClick={() =>
            navigate("/login")
          }

          className="
            mt-6
            rounded-full
            bg-[var(--accent)]
            px-7
            py-3
            font-semibold
            text-black
          "
        >
          Login
        </button>
      </div>
    );
  }


  // ==========================================
  // PROJECT NOT FOUND
  // ==========================================

  if (!project) {
    return (
      <div
        className="
          flex
          min-h-screen
          items-center
          justify-center
          bg-[var(--bg-main)]
        "
      >
        Project not found.
      </div>
    );
  }


  // ==========================================
  // PAGE
  // ==========================================

  return (
    <div
      className="
        min-h-screen
        w-full
        min-w-0

        overflow-x-auto
        overflow-y-auto

        bg-[var(--bg-main)]
        text-white
      "
    >

      {/* HIDDEN COMPILED AUDIO PLAYER */}

      <audio
        ref={audioRef}
        onEnded={handleEnded}
      />


      {/* HIDDEN UPLOAD INPUT */}

      <input
        ref={fileInputRef}

        type="file"

        accept="audio/*"

        hidden

        onChange={
          handleFileChange
        }
      />


      {/* ======================================
          TOP BAR
      ====================================== */}

      <div
        className="
          sticky
          top-0
          z-[150]

          flex
          min-w-full

          items-center
          justify-between

          border-b
          border-white/10

          bg-[#090d0c]

          px-6
          py-3
        "
      >

        {/* PROJECT INFORMATION */}

        <div>
          <h1
            className="
              text-lg
              font-semibold
            "
          >
            {project.name}
          </h1>

          <p
            className="
              mt-0.5
              text-[11px]
              text-gray-500
            "
          >
            Version{" "}
            {project.version}
          </p>
        </div>


        {/* PROJECT MENU */}

        <div
          ref={menuRef}
          className="relative"
        >
          <button
            type="button"

            onClick={() =>
              setShowProjectMenu(
                (previous) =>
                  !previous
              )
            }

            className="
              flex
              h-10
              w-10

              cursor-pointer

              items-center
              justify-center

              rounded-full

              text-gray-300

              transition

              hover:bg-white/10
              hover:text-white
            "
          >
            <MoreVertical
              size={22}
            />
          </button>


          {showProjectMenu && (
            <div
              className="
                absolute
                right-0
                top-12
                z-[200]

                w-48

                overflow-hidden

                rounded-xl

                border
                border-white/10

                bg-[#121716]

                shadow-2xl
              "
            >

              <button
                type="button"

                onClick={() => {
                  setShowProjectMenu(
                    false
                  );

                  handleUploadButton();
                }}

                disabled={
                  uploading
                }

                className="
                  flex
                  w-full

                  cursor-pointer

                  items-center
                  gap-3

                  px-4
                  py-3

                  text-sm
                  text-gray-200

                  transition

                  hover:bg-white/10

                  disabled:cursor-not-allowed
                  disabled:opacity-50
                "
              >
                <Upload size={16} />

                {uploading
                  ? "Uploading..."
                  : "Upload Audio"}
              </button>


              <button
                type="button"

                onClick={
                  handleExport
                }

                className="
                  flex
                  w-full

                  cursor-pointer

                  items-center
                  gap-3

                  px-4
                  py-3

                  text-sm
                  text-gray-200

                  transition

                  hover:bg-white/10
                "
              >
                <Download
                  size={16}
                />

                Export Audio
              </button>

            </div>
          )}
        </div>

      </div>


      {/* ======================================
          EFFECT RIBBON
      ====================================== */}

      <EditingRibbon
        selectedClip={
          selectedClip
        }

        onEffectSelect={
          handleApplyEffect
        }

        onUndo={
          handleUndo
        }

        onRedo={
          handleRedo
        }

        canUndo={
          undoStack.length > 0
        }

        canRedo={
          redoStack.length > 0
        }
      />


      {/* ======================================
          MAIN PREVIEW WORKSPACE
      ====================================== */}

      <div
        className="
          min-h-[300px]
          min-w-full

          border-b
          border-white/10

          bg-[#050708]
        "
      >

        {project.state
          ?.tracks
          ?.length === 0 ? (

          // ====================================
          // EMPTY PROJECT
          // ====================================

          <div
            className="
              flex
              min-h-[300px]

              flex-col

              items-center
              justify-center
            "
          >
            <Upload
              size={40}

              className="
                text-[var(--accent)]
              "
            />

            <h2
              className="
                mt-5

                text-xl
                font-semibold
              "
            >
              Add your first audio
            </h2>

            <p
              className="
                mt-2

                text-sm
                text-gray-500
              "
            >
              Upload an audio file
              to start editing.
            </p>

            <button
              type="button"

              onClick={
                handleUploadButton
              }

              disabled={
                uploading
              }

              className="
                mt-6

                cursor-pointer

                rounded-full

                bg-[var(--accent)]

                px-6
                py-3

                font-semibold
                text-black

                disabled:cursor-not-allowed
                disabled:opacity-50
              "
            >
              {uploading
                ? "Uploading..."
                : "Upload Audio"}
            </button>

          </div>

        ) : (

          // ====================================
          // COMPILED WAVEFORM
          // ====================================

          <PreviewWaveform
            audioUrl={
              previewUrl
            }

            currentTime={
              markerTime
            }

            duration={
              duration
            }
          />

        )}

      </div>


      {/* ======================================
          PLAYBACK CONTROLS
      ====================================== */}

      <EditorControls
        isPlaying={
          isPlaying
        }

        onPlayPause={
          handlePlayPause
        }

        currentTime={
          markerTime
        }

        duration={
          duration
        }
      />


      {/* ======================================
          TIMELINE
      ====================================== */}

      <Timeline
        project={
          project
        }

        updateProjectState={
          updateProjectState
        }

        markerTime={
          markerTime
        }

        setMarkerTime={
          setMarkerTime
        }

        isPlaying={
          isPlaying
        }

        trackMarkers={
          trackMarkers
        }

        setTrackMarkers={
          setTrackMarkers
        }

        selectedClip={
          selectedClip
        }

        setSelectedClip={
          setSelectedClip
        }
      />

    </div>
  );
};


export default ProjectEditor;